
platform :ios, '10.0'
use_frameworks!

def all_pods(file)
  file_path = File.expand_path(file)
  if !File.exists? file_path
    return [];
  end
  pods_array = []
  skip_line_start_symbols = ["#", "/"]
  File.foreach(file_path) { |line|
    next if skip_line_start_symbols.any? { |symbol| line =~ /^\s*#{symbol}/ }
    pods_array.push(line);
  }
  return pods_array
end

target 'PodfileExample_Example' do

  file_array = ['Pod_Business.rb', 'Pod_UI.rb']
  file_array.map { |file|
    pods_array = all_pods(file)
    pods_array.map { |line|
      array = line.split(",")
      name = array[0].strip()
      if array.length == 2
        version = array[1].strip()
        pod name, version
        elsif array.length == 3
        path = array[2].strip()
        pod name, :path => path
        else
        pod name
      end
    }
  }
  
  #其他第三方
  pod 'LookinServer', :configurations => ['Debug']	#UI调试
  
end
